rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about,name='about'),
        url(r'^contact/$', views.contact ,name='contact'),
        url(r'^contact_messages/$', views.contact_messages,name='contact_messages'),
        url(r'^restricted/$',views.restricted, name = 'restricted'),
        #url(r'^search/$',views.search, name = 'search'),
        url(r'^goto/$',views.track_url, name = 'goto'),
        url(r'^like_category/$', views.like_category, name='like_category'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page'),
        url(r'^gallery/$', views.gallery, name='gallery'),
        #url(r'^page_index/$', views.page_index,name='page_index'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[-\w]+)/add_page/$', views.add_page, name='add_page'),
        url(r'^category/(?P<category_name_slug>[-\w]+)/$', views.category, name='category'),
        # Registration Removed | Redux is active now
        #url(r'^register/$',views.register, name='register'),
        #url(r'^login/$', views.user_login, name='login'),
        #url(r'^logout/$', views.user_logout, name='logout'),
)

twd/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

#creat a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'twd.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^gmail/', include('gmail.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
        name = models.CharField(max_length=128, unique=True)
        views = models.IntegerField(default=0)
        likes = models.IntegerField(default=0)
        slug = models.SlugField(unique=True)

        def save(self, *args, **kwargs):
                self.slug = slugify(self.name)
                super(Category, self).save(*args, **kwargs)

        def __unicode__(self):
                return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Contact(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField(max_length=75)
    subject = models.CharField(max_length=128)
    message = models.TextField()

    def __str__(self):
        return self.subject


class UserProfile(models.Model):
    # This line is required.Links Userprofile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override th __unicode__() method to return out something meaningful!
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, Contact, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.CharField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty and doesn't start with 'http://', prepend 'http://'.
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

        return cleaned_data

class ContactForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Name")
    email = forms.EmailField(max_length=75, help_text="Email")
    subject = forms.CharField(max_length=128, help_text="Subject")
    message = forms.CharField(widget=forms.Textarea,help_text="Enter your message here")

    class Meta:
        model = Contact
        fields = ('name','email','subject','message')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category, Page, Contact
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.forms import CategoryForm, PageForm, ContactForm, UserForm, UserProfileForm
from datetime import datetime
from rango.bing_search import run_query

import os

def index(request):

    category_list = Category.objects.order_by('-name')[:5]
    page_list = Page.objects.order_by('-title')[:5]

    context_dict = {'categories': category_list, 'pages': page_list}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).days > 0:
            # ...reassign the value of the cookie to +1 of what it was before...
            visits = visits + 1
            # ...and update the last visit cookie, too.
            reset_last_visit_time = True
    else:
        # Cookie last_visit doesn't exist, so create it to the current date/time.
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits
    context_dict['visits'] = visits

    response = render(request,'rango/index.html', context_dict)

    return response







def about(request):
    context_dict = {}
    context_dict['abc'] = 'We are here'
    return render(request, 'rango/about.html', context_dict)


def category(request, category_name_slug):
    context_dict = {}
    context_dict['result_list'] = None
    context_dict['query'] = None
    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)

            context_dict['result_list'] = result_list
            context_dict['query'] = query

    try:
        category = Category.objects.get(slug=category_name_slug)
        context_dict['category_name'] = category.name
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        pass

    if not context_dict['query']:
        context_dict['query'] = category.name

    return render(request, 'rango/category.html', context_dict)




#Add Category Veiw
@login_required
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index (request)
        else:
            print (form.errors)
    else:
        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form':form})







def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            form.save(commit=True)
            return index (request)
        else:
            print (form.errors)
    else:
        form = ContactForm()

    return render(request, 'rango/contact_form.html', {'form':form})








# Add Page View
@login_required()
def add_page(request,category_name_slug):
    try:
        cat = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
                cat = None

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if cat:
                page = form.save(commit=False)
                page.category = cat
                page.views = 0
                page.save()
                # probably better to use a redirect here.

                #return HttpResponseRedirect(reverse('rango:category',args=[cat.slug]))
                return redirect(reverse('rango:category',args=[category_name_slug]))
            print (form.errors)
    else:
        form = PageForm()

    context_dict = {'form':form, 'category': cat}

    return render(request, 'rango/add_page.html', context_dict)






def contact_messages(request):
    message_list = Contact.objects.all()
    context_dict = {'messages': message_list}
    return render(request,'rango/contact_messages.html',context_dict,)


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


def search(request):

    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()

        if query:
            # Run our Bing function to get the results list!
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list})


def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        page_id = request.GET['page_id']
        try:
            page = Page.objects.get(id=page_id)
            page.views = page.views + 1
            page.save()
            url = page.url
        except:
            pass

    return redirect(url)


@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id  = request.GET['category_id']

    likes = 0

    if cat_id:
        cat = Category.objects.get(id=int(cat_id))
        if cat:
            likes = cat.likes + 1
            cat.likes = likes
            cat.save()
    return HttpResponse(likes)


#Helper Function for Inline Category Suggestions
def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

        if max_results > 0:
            if len(cat_list) > max_results:
                cat_list = cat_list[:max_results]

        return cat_list


def suggest_category(request):

        cat_list = []
        starts_with = ''
        if request.method == 'GET':
                starts_with = request.GET['suggestion']
        if len(starts_with) > 0:
            cat_list = get_category_list(8, starts_with)
        else:
            cat_list = Category.objects.all()

        return render(request, 'rango/category_list.html', {'cat_list': cat_list })


def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict = {}

    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category = category, title = title, url = url)

            pages = Page.objects.filter(category=category).order_by('-views')

            # Adds our results list to the template context under name pages.
            context_dict['pages'] = pages
    return render(request, 'rango/page_list.html', context_dict)



def gallery(request):

    BASE_DIR = os.path.dirname(os.path.dirname(__file__))
    img_folder = 'static/gallery/'
    images_path = (
    os.path.join(BASE_DIR, img_folder)
)

    img_list =os.listdir(images_path)
    return render(request, 'rango\gallery.html', {'images': img_list})

templates/rango/about.html
{% extends 'base.html' %}

{% load staticfiles %}


{% block title %} About Rango {% endblock %}


{% block body_block %}
    <div class="page-header">
        <h1>About Rango</h1>
    </div>

    <div>
        <p>This is <strong>Rango's About Page.</strong></p>
        <img width="500" height="500" src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
    </div>
{% endblock %}

templates/rango/add_category.html
{% extends 'base.html' %}
{% block title %} Add a new category! {% endblock %}
{% block body_block %}
        <h1>Add a Category</h1>
        <form id="category_form" method="post" action="/rango/add_category/"/>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}

            <input type="submit" name="submit" value="Create Category"/>
        </form>

{% endblock %}

templates/rango/add_page.html
{% extends 'base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}
{% if category %}

                <form role="form"  id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}

                <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
                </form>
            {%  else %}
            <p>This is category does not exist.</p>
        {%  endif %}


        {% endblock %}

templates/rango/category.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}


<div class="pannel">
    <h1>Category: {{ category_name }}</h1>


    {% if category %}
    <!-- Pages -->
    <div id="pages">
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
            {% if page.views > 1%}
            <span class="label label-info">{{page.views }} views</span>
            {% elif page.views == 1 %}
            <span class="label label-info">{{ page.views }} view</span>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    <p>

        <strong id="like_count">{{ category.likes }}</strong> people like this category

        {% if user.is_authenticated %}
        <button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
            <span class="glyphicon glyphicon-thumbs-up"></span>
            Like
        </button>
        {% endif %}

    </p>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}
    </div>
    <!-- Navigation -->
    {% if user.is_authenticated %}
    <h4><a href="/rango/category/{{category.slug}}/add_page/">Add a Page</a></h4>
    {% endif %}


    <h2>Search and Add Your Favourite Page</h2>

    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:category' category.slug %}">
        {% csrf_token %}
        <!-- Display the search form elements here -->
        <input class="form-control" type="text" size="50" name="query" value="" id="query"/>
        <input class="btn btn-primary" type="submit" name="submit" value="Search"/>
        <br/>
    </form>

    {% if result_list %}
    <div class="panel-heading">
        <h3 class="panel-title">Results</h3>
        <!-- Display search results in an ordered list -->
        <div class="panel-body">
            <div class="list-group"></div>
            <div class="list-group">{% for result in result_list %}
                <div class="list-group-item">

                    <h4 class="list-group-item-heading">
                        <button class="btn btn-xs btn-success add-page" type="button"
                                data-catid="{{ category.id }}" data-url="{{ result.link }}" data-title="{{ result.title }}">
                            <span class="glyphicon glyphicon-plus"></span>
                            Add
                        </button>
                        <a href="{{ result.link }}"> {{ result.title }}</a>
                    </h4>

                    <p class="list-group-item-text">{{ result.summary }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>


    {% else %}
    <p>The specified category {{ category_name }} does not exist!</p>
    {% endif %}

    {% endblock %}
</div>

templates/rango/category_list.html
{% if cat_list %}
    <ul class="nav nav-sidebar">
    {% for c in cat_list %}
    {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
            <a href="{% url 'rango:category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}


{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

templates/rango/cats.html
{% if cats %}
    <ul class="nav nav-sidebar">
    {% for c in cats %}
    {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
            <a href="{% url 'rango:category'  c.slug %}">{{ c.name }}</a></li>
    {% endfor %}


{% else %}
    <li> <strong >There are no category present.</strong></li>

    </ul>
{% endif %}

templates/rango/contact_form.html
{% extends 'base.html' %}
{% block body_block %}
{% block title %}Contact Us{% endblock %}
        <h1>Contact Form</h1>
        <form id="contact_form" method="post" action="{% url 'rango:contact' %}"/>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                <p>{{ field }}</p>
            {% endfor %}

            <input type="submit" name="submit" value="Submit the Message"/>
        </form>

{% endblock %}

templates/rango/contact_messages.html
{% extends 'base.html' %}
{% block title %}contact Messages{% endblock %}

{% block body_block %}
    <h1>Rango says..hello world!</h1>
        {% if messages %}
            <table>
                {% for msg in messages %}
                <tr>
                    <td>{{ msg.name }}</td>
                    <td>{{ msg.email }}</td>
                    <td>{{ msg.subject }}</td>
                    <td>{{ msg.message }}</td>
                </tr>
                {% endfor %}
            </table>
       {% else %}
            <strong>There are no messages present.</strong>
       {% endif %}
        <li><a href="/rango/add_category/">Add a New Category</a></li>

{% endblock %}

templates/rango/page_index.html
{% extends 'base.html' %}
{% block title %}Page Index{% endblock %}
{% block body_block %}

        <h1>Rango says..hello world!</h1>

        {% if pages %}
            <table>
                {% for page in pages %}
                <tr>
                    <td>{{ page.category }}</td>
                    <td>{{ page.title }}</td>
                    <td>{{ page.url }}</td>
                    <td>{{ page.views }}</td>
                </tr>
                {% endfor %}
            </table>
       {% else %}
            <strong>There are no messages present.</strong>
       {% endif %}
        <li><a href="/rango/add_category/">Add a New Category</a></li>

{% endblock %}

templates/rango/page_list.html
{% if pages %}
<ul>
    {% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
        {% if page.views > 1%}
        <span class="label label-info">{{page.views }} views</span>
        {% elif page.views == 1 %}
        <span class="label label-info">{{ page.views }} view</span>
        {% endif %}
    </li>
    {% endfor %}
</ul>
<p>

    <strong id="like_count">{{ category.likes }}</strong> people like this category

    {% if user.is_authenticated %}
    <button id="likes" data-catid="{{category.id}}" class="btn btn-primary" type="button">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        Like
    </button>
    {% endif %}

</p>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}

templates/rango/register.html
{% extends 'base.html' %}
{% block body_block %}
        <h1>Register with Rango</h1>


        {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="/rango/">Return to the homepage.</a><br />
        {% else %}
        Rango says: <strong>register here!</strong><br />

        <form id="user_form" method="post" action="/rango/register/"
                enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}

{% endblock %}

templates/rango/restricted.html
{%  extends 'base.html' %}

{% load staticfiles %}


{% block title %} Restricted Page {% endblock %}
{% block body_block %}


<p class="about"> This is a restricted page <p/>


{% endblock %}

templates/rango/rough.html
{% block body_block %}


    <form class="form-signin" role="form" method="post" action=".">
        {% csrf_token %}

        <h2 class="form-signin-heading">Please sign in</h2>
        <input class="form-control" placeholder="Username" id="id_username" maxlength="254" name="username" type="text"
               required autofocus=""/>
        <input type="password" class="form-control" placeholder="Password" id="id_password" name="password"
               type="password" required/>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit"/>
        Sign in</button>
    </form>

{% endblock %}

templates/rango/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}

    <div class="page-header">
        <h1>Search with Rango</h1>
    </div>

    <div class="row">

        <div class="panel panel-primary">
            <br/>

            <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
                {% csrf_token %}
                <!-- Display the search form elements here -->
                <input class="form-control" type="text" size="50" name="query" value="" id="query" />
                <input class="btn btn-primary" type="submit" name="submit" value="Search" />
                <br />
            </form>

            <div class="panel">
                {% if result_list %}
                    <div class="panel-heading">
                    <h3 class="panel-title">Results</h3>
                    <!-- Display search results in an ordered list -->
                    <div class="panel-body">
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading"><a href="{{ result.link }}">{{ result.title }}</a></h4>
                                    <p class="list-group-item-text">{{ result.summary }}</p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
                </div>
            </div>
 </div>

{% endblock %}