gmail/urls.py
from django.conf.urls import patterns, url
from gmail import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^$', views.index, name='index'),
        url(r'^(?P<fv>[\d]+)/(?P<sv>[\d]+)/$', views.sumup, name='sumup'),
        url(r'^(?P<your_name>[\w\-\s]+)/$', views.personalized_name, name='personalized_name'),
)

rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^about/$', views.about,name='about'),
        url(r'^contact/$', views.contact ,name='contact'),
        url(r'^contact_messages/$', views.contact_messages,name='contact_messages'),
        url(r'^restricted/$',views.restricted, name = 'restricted'),
        #url(r'^search/$',views.search, name = 'search'),
        url(r'^goto/$',views.track_url, name = 'goto'),
        url(r'^like_category/$', views.like_category, name='like_category'),
        url(r'^suggest_category/$', views.suggest_category, name='suggest_category'),
        url(r'^auto_add_page/$', views.auto_add_page, name='auto_add_page'),
        url(r'^gallery/$', views.gallery, name='gallery'),
        #url(r'^page_index/$', views.page_index,name='page_index'),
        url(r'^add_category/$', views.add_category, name='add_category'),
        url(r'^category/(?P<category_name_slug>[-\w]+)/add_page/$', views.add_page, name='add_page'),
        url(r'^category/(?P<category_name_slug>[-\w]+)/$', views.category, name='category'),
        # Registration Removed | Redux is active now
        #url(r'^register/$',views.register, name='register'),
        #url(r'^login/$', views.user_login, name='login'),
        #url(r'^logout/$', views.user_logout, name='logout'),
)

twd/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

#creat a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, request, user):
        return '/rango/'

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'twd.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace='rango')),
    url(r'^gmail/', include('gmail.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)

# UNDERNEATH your urlpatterns definition, add the following two lines:
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
 {% load rango_extras %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon/favicon.ico' %}">

    <title>Serenity - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>



<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/rango/">Serenity</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'rango:index' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><span class="navbar-text">Welcome, {{ user.username | capfirst }}!</span></li>
                    <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                    <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                    <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                    <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:gallery' %}">Gallery</a></li>

            </ul>
        </div>
    </div>

</div>

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">


            {% block side_block %}
            <ul class="nav nav-list">
                <li class="nav-header">Find a Category</li>
                <form>
                    <label></label>
                    <li><input class="search-query span10" type="text" name="suggestion" value="" id="suggestion"/></li>
                </form>
            </ul>

            <div id="cats">
                {% get_category_list category %}
            </div>



            {% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <div>
                {% block body_block %}{% endblock %}
                {% block like_website %}
                <div class="row">
                <div id="likerango" class="col-md-6">
                <button class="likew btn btn-success btn-xs">Like Rango!</button>
                </div>
                </div>
                {% endblock %}
            </div>
        </div>
    </div>
</div>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<script src="{% static 'js/rango-jquery.js' %}"></script>
<script src="{% static 'js/rango-ajax.js' %}"></script>



<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

templates/base1.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    </head>

    <body>
        <div>
        {%  block header %}
            <div id="header">
            {% if user.is_authenticated %}
                <h1>Hello {{ user.username | capfirst}}!</h1>
            {% else %}
            <h1>Hello world!</h1>
            {% endif %}
            </div>
        {% endblock %}
            {% block body_block %}{% endblock %}
        </div>

        <hr />

        <div>
            <ul>

            <li><a href="{% url 'rango:index' %}">Index</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted</a> </li>
                <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>

                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
            {% else %}
                <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}

            <li><a href="{% url 'rango:about' %}">About</a></li>
            </ul>
        </div>

    </body>
</html>